### ISSUE TITLE
brain MRI images

### ISSUE THREAD

**Issue by mahilaMoghadami** [jianqingzheng/res_aligner_net#1]
Hello
thank you for your implementation sharing
Its interesting 

Can I use your code in my dataset which is brain MRI images (T1, T2 and flair) images with .dicom format?
if yes, how?

appreciate your response.
thank you

**Comment by jianqingzheng** [comment]
> Hello thank you for your implementation sharing Its interesting
> 
> Can I use your code in my dataset which is brain MRI images (T1, T2 and flair) images with .dicom format? if yes, how?
> 
> appreciate your response. thank you

Many thanks for your interest.

Because the data format used by this code is .nii or .nii.gz, it would be great if you could convert the DICOM files into NIfTI format, and then organize the data in the following structure:
```
[$DOWNLOAD_DIR]/res_aligner_net/           
├── data/[$data_name]/dataset
|   |   # experimental dataset for training and testing (.nii|.nii.gz files)
|   ├── train/
|   |	├── images/
|   |   |   ├──0001.nii.gz
|   |   |   └── ...
|   |	├── labels/
|   |   |   ├──0001.nii.gz
|   |   |   └── ...
|   ├── test/
|   |	├── images/
|   |   |   ├──0001.nii.gz
|   |   |   └── ...
|   |	└── labels/
|   |       ├──0001.nii.gz
|   |       └── ...
```
Afterward, you can directly follow the instructions provided in the [README.md file](https://github.com/jianqingzheng/res_aligner_net/blob/main/README.md) to train and use it.
